spring.application.name=68-booking-system-backend
server.port=9191
spring.datasource.url=jdbc\:h2\:mem\:bookingdb\n
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true\n
spring.h2.console.enabled=true
